version: "2.3"

services:
  rviz:
    image: husarion/rviz2
    restart: unless-stopped
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
    
  micro-ros_agent:
    image: microros/micro-ros-agent:galactic
    command: serial --dev /dev/ttyUSB0 -b 921600
    devices: 
      - /dev/ttyUSB0:/dev/ttyUSB0

